#!/bin/bash
echo ""
echo "=== Voxtype Post-Installation ==="
echo ""
echo "To complete setup:"
echo ""
echo "  1. Download a whisper model:"
echo "     voxtype setup --download"
echo ""
echo "  2. Start voxtype:"
echo "     systemctl --user enable --now voxtype"
echo ""
echo "=== Hotkey Configuration ==="
echo ""
echo "RECOMMENDED: Use compositor keybindings (no special permissions)"
echo ""
echo "  Add to your compositor config:"
echo ""
echo "  Hyprland:  bind = SUPER, V, exec, voxtype record start"
echo "             bindr = SUPER, V, exec, voxtype record stop"
echo ""
echo "  Sway:      bindsym \$mod+v exec voxtype record start"
echo "             bindsym --release \$mod+v exec voxtype record stop"
echo ""
echo "  Then disable built-in hotkey in ~/.config/voxtype/config.toml:"
echo "    [hotkey]"
echo "    enabled = false"
echo ""
echo "ALTERNATIVE: Built-in hotkey (GNOME, KDE, X11)"
echo ""
echo "  If your desktop doesn't support key release events, you can use"
echo "  voxtype's built-in hotkey. This requires the 'input' group:"
echo ""
echo "     sudo usermod -aG input \$USER"
echo "     # Log out and back in for changes to take effect"
echo ""
echo "  WARNING: The input group grants access to ALL keyboard input."
echo "  Only use this if compositor keybindings aren't available."
echo ""
echo "See: https://github.com/peteonrails/voxtype/blob/main/docs/USER_MANUAL.md"
echo ""
