#!/bin/bash
echo ""
echo "=== Voxtype Post-Installation ==="
echo ""
echo "To complete setup:"
echo ""
echo "  1. Add your user to the 'input' group:"
echo "     sudo usermod -aG input \$USER"
echo ""
echo "  2. Log out and back in for group changes to take effect"
echo ""
echo "  3. Enable and start the ydotool daemon:"
echo "     systemctl --user enable --now ydotool"
echo ""
echo "  4. Download a whisper model:"
echo "     voxtype setup --download"
echo ""
echo "  5. Start voxtype:"
echo "     systemctl --user enable --now voxtype"
echo ""
